dist: xenial
sudo: required
before_install:
     - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
     - sudo apt-add-repository -y ppa:beineri/opt-qt-5.12.0-xenial
     - sudo apt-get -qq update
install:
     - sudo apt-get -qq install g++-4.8 libc6-i386 qt512tools qt512svg  qt512webengine qt512serialport
     - PATH="/opt/qt512/bin:$PATH"
     - qt512-env.sh 
     - wget 'https://s3-us-west-2.amazonaws.com/ucsolarteam.hostedfiles/astyle'
     - tar -zxvf astyle
     - (cd ./astyle/build/gcc && make release && sudo make install)
     - rm astyle -rf
script:
     - "! (astyle *.h *.cpp -r --dry-run --options=astylerc | grep Formatted)"
     - cd Recruit-Training/Advanced-Recruit-Training/src 
     - qmake
     - make

language: cpp
